config/routes.rb
Rails.application.routes.draw do

   resources :homes
   root "homes#index"

end

app/models/home.rb
class Home < ActiveRecord::Base

	validates_presence_of :full_name, :occupation
	validates_length_of :description, allow_blank: false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


   def new
        @home = Home.new
    end

    def show
         @home = Home.find(params[:id])
    end

  def create
    @home = Home.new(home_params)

      if @home.save
         redirect_to @home, notice: 'Cadastro criado com sucesso!'
      else
         render action: :new
      end
    end

private

    def home_params
    	params.require(:home).permit(:full_name, :occupation, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/_about.html.erb
<div id="about">
                    <section class="clearfix">
                        <div class="g2">
                            <div class="photo">
                                <%= image_tag( "foto.png" ,alt: "Rodolfo Peixoto") %>
                            </div>
                            <div class="info">
                                <h2>
                                    Rodolfo Peixoto
                                </h2>
                                <h6>
                                    Desenvolvedor / Graduando Ciências da Computação
                                </h6>
                                <p>
                                    Um grande entusiasta por computação e empreendedorismo, Eu me dedico a estudar arduamente várias áreas da computação para um dia desenvolver projetos que traga benefícios para a sociedade brasileira ou quem sabe do mundo.
                                </p>
                            </div>
                        </div>
                        <div class="g1">
                            <div class="main-links sidebar">
                                <ul>
                                    <li>
                                        <a href="#resume">Resumo</a>
                                    </li>
                                    <li>
                                        <a href="#portfolio">Portfolio</a>
                                    </li>
                                    <li>
                                        <a href="#contact">Contrate-me para o seu próximo projeto</a>
                                    </li>

                                </ul>
                            </div>
                        </div>

                        <div class="break"></div>

                        <div class="contact-info">
                          <div class="g1">
                            <div class="item-box clearfix">
                              <i class="icon-envelope"></i>
                              <div class="item-data">
                                <h3><a href="#">rodolfog.peixoto@gmail.com
                                 <i class="fa fa-envelope"></i>
                                </a>
                                </h3>

                                <p>Email</p>
                              </div>
                            </div>
                          </div>

                          <div class="g1">
                            <div class="item-box clearfix">
                              <i class="icon-facebook"></i>
                              <div class="item-data">
                                <h3><a href="https://www.facebook.com/rdxinho">@rdxinho
                                <i class="fa fa-facebook-square"></i>
                                </a></h3>
                                <p>Facebook</p>
                              </div>
                            </div>
                          </div>



                          <div class="g1">
                            <div class="item-box clearfix">
                              <i class="icon-twitter"></i>
                              <div class="item-data">
                                <h3><a href="https://twitter.com/rdxinho" title="Twitter Rodolfo Peixoto" alt="Twitter - Rodolfo Peixoto">@rdxinho
                                <i class="fa fa-twitter-square"></i>
                                </a></h3>
                                <p>Twitter</p>
                              </div>
                            </div>
                          </div>
                           
                        <div class="break"></div>

                          <div class="g1">
                            <div class="item-box clearfix">
                              <i class="icon-facebook"></i>
                              <div class="item-data">
                                <h3><a href="http://br.linkedin.com/pub/rodolfo-peixoto/76/51b/599">Linkind
                                <i class="fa fa-linkedin-square"></i>
                                </a></h3>
                                <p>Linkind Perfil</p>
                              </div>
                            </div>
                          </div>


                        <div class="g1">
                            <div class="item-box clearfix">
                              <i class="icon-facebook"></i>
                              <div class="item-data">
                                <h3><a href="https://github.com/rodolfopeixoto">
                                GitHub
                                <i class="fa fa-github"></i>
                                </a></h3>
                                <p>GitHub Profile</p>
                              </div>
                            </div>
                          </div>


                          <div class="g1">
                            <div class="item-box clearfix">
                              <i class="icon-facebook"></i>
                              <div class="item-data">
                                <h3><a href="https://gitlab.com/u/rdxinho">
                                GitLab
                                <i class="fa fa-github-alt"></i>
                                </a></h3>
                                <p>GitLab Profile</p>
                              </div>
                            </div>
                          </div>


                        </div>

                    </section><!-- content -->
                </div>

app/views/homes/_contato.html.erb
<div id="contact">
                    <section class="clearfix">
                       <div class="g1">
                         <div class="sny-icon-box">
                           <div class="sny-icon">
                              <i class="icon-globe"></i>
                            </div>
                            <div class="sny-icon-content">
                              <h4>Endereço</h4>
                              <p>Campos dos Goytacazes</p>
                            </div>
                         </div>
                       </div>
                       <div class="g1">
                         <div class="sny-icon-box">
                           <div class="sny-icon">
                              <i class="icon-phone"></i>
                            </div>
                            <div class="sny-icon-content">
                              <h4>Telefone</h4>
                              <p>(22) 9 9843-0303<br/> (22) 9 8813-0843 </p>
                            </div>
                         </div>
                       </div>
                       <div class="g1">
                         <div class="sny-icon-box">
                           <div class="sny-icon">
                              <i class="icon-user"></i>
                            </div>
                            <div class="sny-icon-content">
                              <h4>Rodolfo Peixoto</h4>
                              <p>Eu sou apaixonado pela computação e faço dessa paixão o meu trabalho. Quando se ama o que faz, tudo saí mais bonito.</p>
                            </div>
                         </div>
                       </div>
                       <div class="break"></div>
                       
                    </section>
                </div>

app/views/homes/_footer.html.erb
        <footer>
            <p>
                Todos os direitos reservados a Rodolfo Peixoto &copy; 2014
            </p>
        </footer>

app/views/homes/_header.html.erb
<header id="header">
            <div id="logo">
                <h2>
                    Rodolfo Peixoto
                </h2>
                <div class="imgperfil">
                                <%= image_tag( "foto.png" ,alt: "Rodolfo Peixoto") %>
                            </div>
                <h4 class="what">
                    Desenvolvedor / Graduando em Ciências da Computação
                </h4>
            </div>
        </header>

app/views/homes/_menu.html.erb
<ul class='etabs'>
                <li class='tab' id="tab-about">
                  <a href="#about"><i class="icon-user"></i><span> Rodolfo Peixoto</span></a>
                </li>
                <li class='tab'>
                  <a href="#resume"><i class="icon-file-text"></i><span> Currículo </span></a>
                </li>
                <li class='tab'>
                  <a href="#portfolio"><i class="icon-heart"></i><span> Portfolio</span></a>
                </li>
                <li class='tab'>
                  <a href="#contact"><i class="icon-envelope"></i><span> Contato</span></a>
                </li>
            </ul>

app/views/homes/_portfolio.html.erb
<div id="portfolio">
                    <section class="clearfix">

                        <div class="g1">
                            <div class="image">
                                <%= image_tag("Marca.png", alt:"Oralix") %>
                                <div class="image-overlay">
                                    <div class="image-link">
                                        <a href="http://www.oralix.com.br" class="btn">Acessar</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--

                        <div class="break"></div>

                        <div class="g1">
                            <div class="image">
                                <img src="http://lorempixel.com/306/306/sports/4" alt="">
                                <div class="image-overlay">
                                    <div class="image-link">
                                        <a href="http://lorempixel.com/606/606/sports/4" class="btn">Acessar
</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="g1">
                            <div class="image">
                                <img src="http://lorempixel.com/306/306/sports/5" alt="">
                                <div class="image-overlay">
                                    <div class="image-link">
                                        <a href="http://lorempixel.com/606/606/sports/5" class="btn">Acessar</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="g1">
                            <div class="image">
                                <img src="http://lorempixel.com/306/306/business/2" alt="">
                                <div class="image-overlay">
                                    <div class="image-link">
                                        <a href="http://lorempixel.com/606/606/business/2" class="btn">Acessar</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        -->
                        
                    </section>
                </div>

app/views/homes/_resume.html.erb
<div id="resume">
                    <section class="clearfix">
                        <div class="g2">
                            <h3>
                                Experiência de Trabalho
                            </h3>
                            <ul class="no-list work">
                                <li>
                                    <h5>
                                        Freelance Web Designer
                                    </h5><span class="label label-info">2007-2014</span>
                                    <p>
                                        Desenvolvi vários sites web, porém fiquei dois anos sem desenvolver e as tecnologias ficaram defasadas, o que é normal no ramo da computação e agora estou voltando e com mais bagagem e conhecimento para desenvolver sistemas mais robustos e completo.
                                    </p>
                                </li>
                                <li>
                                    <h5>
                                        Analista de Suporte Técnico Jr. - CTIS
                                    </h5><span class="label label-info">2013-2014</span>
                                    <p>
                                        Trabalhei como analista de suporte computacional junior na CTIS, prestavamos serviço para a rede PETROBRAS, foi uma ótima experiência, pois pude ter o contato com uma grande empresa e a adquirir conhecimento para ser mais profissional ainda.
                                    </p>
                                </li>
                                <li>
                                    <h5>
                                        Litoral Tintas - Auxiliar Administrativo
                                    </h5><span class="label label-info">2011-2012</span>
                                    <p>
                                        Trabalhei desenvolvendo panfletos promocionais, cartas e envelopes personalizados para a empresa. Comecei a desenvolver o site da empresa, mas não pude dar continuidade, pois havia passado para a UNIVERSIDADE ESTADUAL DO NORTE FLUMINENSE para cursa CIÊNCIAS DA COMPUTAÇÃO.
                                    </p>
                                </li>

                            </ul>
                            <h3>
                                Educação
                            </h3>
                            <ul class="no-list work">
                                <li>
                                    <h5>
                                        Estácio de Sá - Sistema de Infomação
                                    </h5><span class="label label-success">2010-2011</span>
                                    <p>
                                        Cursei sistema de informação, porém eu queria mais, gostaria de ter conhecimento não só em software, mas também em hardware e ser um profissional completo.
                                    </p>
                                </li>
                                <li>
                                    <h5>
                                        Universidade Estadual do Norte Fluminente(UENF) - Ciências da Computação
                                    </h5><span class="label label-warning">2012-2017</span>
                                    <p>
                                        Cursando Ciências da Computação e a cada dia eu vejo que fiz a escolha certa, pois estou o curso abrange tanto hardware, quanto software.
                                    </p>
                                </li>
                            </ul>
                        </div>
                        <div class="g1">
                            <div class="sidebar">
                                <h3>
                                    Habilidades
                                </h3>
                                <h5>
                                    Software
                                </h5>
                                <div class="meter emerald">
                                    <span style="width: 45.3%"><span>Photoshop</span></span>
                                </div>
                                <div class="meter carrot">
                                    <span style="width: 30%"><span>GIMP</span></span>
                                </div>
                                <div class="meter wisteria">
                                    <span style="width: 80%"><span>Sublime Text</span></span>
                                </div>
                                <div class="meter sunflower">
                                    <span style="width: 60%"><span>Eclipse</span></span>
                                </div>
                                <div class="meter midnight">
                                    <span style="width: 70%"><span>Terminal Linux</span></span>
                                </div>
                                <div class="meter pomengrate">
                                    <span style="width: 80%"><span>Microsoft Office</span></span>
                                </div>
                                <div class="meter asbestos">
                                    <span style="width: 75%"><span>Linux</span></span>
                                </div>
                                <div class="break"></div>
                                <h5>
                                    Linguagem de Programação
                                </h5>
                                <div class="meter emerald">
                                    <span style="width: 88.3%"><span>HTML/CSS</span></span>
                                </div>
                                <div class="meter carrot">
                                    <span style="width: 70%"><span>PHP/MySql</span></span>
                                </div>
                                <div class="meter wisteria">
                                    <span style="width: 85%"><span>jQuery/JavaScript</span></span>
                                </div>
                                <div class="meter sunflower">
                                    <span style="width: 75%"><span>Ruby</span></span>
                                </div>
                                <div class="meter asbestos">
                                    <span style="width: 72%"><span>C</span></span>
                                </div>

                                <div class="meter midnight">
                                    <span style="width: 82%"><span>Java</span></span>
                                </div>

                            </div>
                        </div>
                    </section>
                </div>

app/views/homes/index.html.erb
    <div class="main wrapper clearfix">
      <!-- Header Start -->
        <%= render partial: "header" %>
        <!-- Header End -->
        <!-- Main Tab Container -->
        <div id="tab-container" class="tab-container">
          <!-- Tab List -->
            <%= render partial: "menu" %>
          <!-- End Tab List -->
            <div id="tab-data-wrap">
              <!-- About Tab Data -->
                <%= render partial: "about" %>
              <!-- End About Tab Data -->
              <!-- Resume Tab Data -->
                <%= render partial: "resume" %>
              <!-- End Resume Tab Data -->
              <!-- Portfolio Tab Data -->
                <%= render partial: "portfolio" %>
              <!-- End Portfolio Data -->
              <!-- Contact Tab Data -->
                <%= render partial: "contato" %>
              <!-- End Contact Data -->
            </div>
        </div>
        <!-- End Tab Container -->
    <%= render partial: "footer" %>
    </div><!-- #main -->

app/views/homes/new.html.erb
<h1>Cadastro Home</h1>

<%= form_for @home do |f| %>
     
     <p>
          <%= f.label :full_name %><br /> 
          <%= f.text_field :full_name %>
     </p>
        <%= f.label :occupation %><br /> 
          <%= f.text_field :occupation %>
     <p>
     <p>
          <%= f.label :description %><br /> 
          <%= f.text_area :description %>
     </p>

     <p>
           <%= f.submit %>
     </p>

<% end %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<h2>Administrador: <%= @home.full_name %></h2>

<ul>
	 <li>Profissão: <%= @home.occupation %></li>
	 <li>Descrição: <%= @home.description %></li>
</ul>

<%= link_to 'Editar Administrador', edit_home_path(@home) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Rodolfo Peixoto - Graduando em Ciências da Computação </title>
  <meta name="description" content="Um grande entusiasta por computação e empreendedorismo, Rodolfo Peixoto se dedica a estudar arduamente várias áreas da computação para um dia desenvolver projetos que traga benefícios para a sociedade brasileira ou quem sabe do mundo.">
 
   <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
  <%= favicon_link_tag 'favicon.ico' %>

  <link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  
   <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">


  <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
      <script>window.html5 || document.write('<script src="assets/javascripts/vendor/
html5shiv.js"><\/script>')</script>
      <![endif]-->


</head>
  <body class="bg-fixed bg-1">
<!--[if lt IE 7]>
    <p class="chromeframe">Você está usando um <strong>antigo</strong> navegador. Por favor <a href="http://browsehappy.com/">atualize o seu navegador</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->
   <div class="main-container">

      <%= yield %>
      
    </div><!-- #main-container -->



</body>
</html>